# Generated by Django 5.0.7 on 2024-07-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagegenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='uploads/')),
                ('prompt', models.TextField(max_length=255)),
                ('quality', models.CharField(choices=[('hd', 'HD'), ('standard', 'Standard')], max_length=225)),
                ('size', models.CharField(choices=[('1024x1024', '1024x1024'), ('1792x1024', '1792x1024'), ('1024x1792', '1024x1792')], max_length=225)),
                ('style', models.CharField(choices=[('vivid', 'Vivid'), ('natural', 'Natural')], max_length=225)),
            ],
        ),
    ]
