# Generated by Django 5.0.7 on 2024-07-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aiimagegen'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimagegen',
            name='ai_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
