# Generated by Django 5.0.7 on 2024-08-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aiimagegen_ai_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimagegen',
            name='ai_image_qr',
            field=models.FileField(default=1, upload_to='ai_gen_qr/'),
            preserve_default=False,
        ),
    ]
